# Make - Build Tool
name: make
description: Build automation tool
category: build-tool

# Capabilities
choose-file: true
has-repl: false
is-package-manager: false

# Commands
command: make
run-file-command: "make -f {file}"
build-command: "make"
clean-command: "make clean"
