# Neovim - Text Editor
name: neovim
description: Hyperextensible Vim-based text editor
category: editor

# Capabilities
choose-file: true
has-repl: false
is-package-manager: false

# Commands
command: nvim
run-file-command: "nvim {file}"
