# Ranger - File Manager
name: ranger
description: Console file manager with VI key bindings
category: file-browser

# Capabilities
choose-file: true
has-repl: true
is-package-manager: false

# Commands
command: ranger
interactive-command: "ranger"
open-dir-command: "ranger {directory}"
