# Go - Programming Language
name: go
description: Open source programming language by Google
category: language

# Capabilities
choose-file: true
has-repl: false
is-package-manager: false

# Commands
command: go
run-file-command: "go run {file}"
build-command: "go build"
test-command: "go test"
install-command: "go install {package}"
